CREATE TABLE IF NOT EXISTS files (
  fileId INTEGER PRIMARY KEY AUTO_INCREMENT,
  fileName VARCHAR(255) NOT NULL UNIQUE,
  filePath VARCHAR(255) NOT NULL,
  fileLinkHash VARCHAR(255) NOT NULL UNIQUE,
  filePassword VARCHAR(255)
);